---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: create a user
      user:
        name: dev123
        shell: /sbin/nologin

    - yum:
        name: httpd
        state: latest

    - service:
        name: httpd
        state: started
